name: tawzeef
description: A new Flutter project.


publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.1
  url_launcher: ^6.3.1
  fcm_config: ^3.6.5
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.1
  riverpod: ^2.6.1
  dio: ^5.8.0+1
  http: ^1.4.0
  bouncing_widget: ^2.0.0
#  auto_animated: ^3.2.0
  delayed_display: ^2.0.0
  flutter_riverpod: ^2.6.1
  google_nav_bar: ^5.0.7
  motion_toast: ^2.14.0
  pin_code_fields: ^8.0.1
  bottom_picker: ^3.2.0
  intl: ^0.19.0
  responsive_framework: ^1.5.1
  photo_view: ^0.15.0
  custom_pop_up_menu: ^1.2.4
  just_bottom_sheet: ^1.3.0
  omni_datetime_picker: ^2.1.1
  shared_preferences: ^2.5.3
  file_picker: 10.1.8
  flutter_pagewise: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - icons/png/
    - icons/svg/

  fonts:
  - family: Tajawal-Bold
    fonts:
      - asset: fonts/Tajawal-Bold.ttf
  - family: Tajawal-Light
    fonts:
      - asset: fonts/Tajawal-Light.ttf
  - family: Tajawal-Medium
    fonts:
      - asset: fonts/Tajawal-Medium.ttf    
  - family: Tajawal-Regular
    fonts:
      - asset: fonts/Tajawal-Regular.ttf
