name: tawzeef
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.7.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0
  url_launcher: ^6.1.12
  fcm_config: ^3.5.2
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.0
  riverpod: ^2.3.6
  dio: ^5.2.1+1
  http: ^1.1.0
  bouncing_widget: ^2.0.0
  auto_animated: ^3.2.0
  delayed_display: ^2.0.0
  flutter_riverpod: ^2.3.6
  google_nav_bar: ^5.0.6
  motion_toast: ^2.7.8
  pin_code_fields: ^8.0.1
  bottom_picker: ^2.0.4
  intl: ^0.18.0
  responsive_framework: ^1.1.0
  photo_view: ^0.14.0
  custom_pop_up_menu: ^1.2.4
  just_bottom_sheet: ^1.3.0
  omni_datetime_picker: ^1.0.7
  awesome_loader_null_safety: ^0.0.2
  shared_preferences: ^2.2.0
  file_picker: ^5.3.2
  flutter_pagewise: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - icons/png/
    - icons/svg/

  fonts:
  - family: Tajawal-Bold
    fonts:
      - asset: fonts/Tajawal-Bold.ttf
  - family: Tajawal-Light
    fonts:
      - asset: fonts/Tajawal-Light.ttf
  - family: Tajawal-Medium
    fonts:
      - asset: fonts/Tajawal-Medium.ttf    
  - family: Tajawal-Regular
    fonts:
      - asset: fonts/Tajawal-Regular.ttf
